In [1]:
import pandas as pd
import json

In [3]:
with open("exemplo.json", "r") as f:
    data = json.load(f)
print(data)

{'articles': [{'date_published': 'Sat, 28 Feb 2026 00:00:00 GMT', 'title': 'EUA x Irã: relembre a cronologia dos protestos no Irã | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/02/28/da-greve-de-comerciantes-ao-ataque-dos-eua-veja-a-cronologia-dos-protestos-no-ira.ghtml'}, {'date_published': 'Sat, 28 Feb 2026 00:00:00 GMT', 'title': 'Companhias aéreas suspendem voos para o Oriente Médio após ataques ao Irã e resposta militar do país | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/02/28/companhias-aereas-suspendem-voos-para-o-oriente-medio-apos-ataques-ao-ira-e-resposta-militar-do-pais.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'Grupo de médicos no Catar vive indefinição sobre retorno ao Brasil | G1', 'url': 'https://g1.globo.com/rs/rio-grande-do-sul/noticia/2026/03/02/grupo-de-medicos-no-catar-vive-indefinicao-sobre-retorno-ao-brasil-apos-tensao-no-oriente-medio-assustados-e-preocupados.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'Estados Unidos x Irã: veja o que é FATO e o que é FAKE na guerra | G1', 'url': 'https://g1.globo.com/fato-ou-fake/noticia/2026/03/02/veja-o-que-e-fato-e-o-que-e-fake-na-guerra-entre-estados-unidos-e-ira-no-oriente-medio.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': "Guerra EUA e Israel x Irã: empresário brasileiro fica 'preso' no Egito | G1", 'url': 'https://g1.globo.com/sp/ribeirao-preto-franca/noticia/2026/03/02/empresario-brasileiro-fica-preso-no-egito-apos-pouso-forcado-em-meio-a-ataques-no-ira-estava-no-espaco-aereo-de-fogo-cruzado.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': "Secretário de Trump diz que guerra contra Irã 'não será eterna' | G1", 'url': 'https://g1.globo.com/mundo/noticia/2026/03/02/secretario-trump-guerra-contra-ira-nao-sera-eterna-objetivos-eua-destruir-ameaca-nuclear.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'Brasileiros no Oriente Médio relatam medo após ataques no Irã | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/02/brasileiros-relatos-ataques-oriente-medio.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'EUA x Irã: brasileiro que voava à Tailândia conta sobre desvio de rota | G1', 'url': 'https://g1.globo.com/sp/sorocaba-jundiai/noticia/2026/03/02/brasileiro-que-viajava-para-tailandia-conta-sobre-desvio-de-rota-e-3-horas-dentro-de-aviao-por-conta-de-ataques-no-ira-foi-um-caos.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'Brasileiros em Dubai relatam tensão após alerta de mísseis | G1', 'url': 'https://g1.globo.com/sp/bauru-marilia/noticia/2026/03/02/brasileira-tensao-alerta-de-misseis-em-dubai.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'EUA afirmam que seis militares americanos morreram no conflito com o Irã | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/02/eua-afirmam-que-seis-militares-americanos-morreram-no-conflito-com-o-ira.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'Legendários não conseguem sair de Dubai após conflito no Oriente Médio | G1', 'url': 'https://g1.globo.com/am/amazonas/noticia/2026/03/02/grupo-de-legendarios-de-manaus-nao-consegue-sair-de-dubai-apos-conflito-no-oriente-medio.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'Grande leva de ataques ao Irã ainda está por vir, diz Trump | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/02/grande-leva-de-ataques-ao-ira-ainda-esta-por-vir-diz-trump.ghtml'}, {'date_published': 'Mon, 02 Mar 2026 00:00:00 GMT', 'title': 'Guerra entre EUA, Israel e Irã fecha aeroportos no Oriente Médio | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/02/guerra-eua-israel-ira-fecha-aeroportos-oriente-medio.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'Guerra fecha espaço aéreo e brasileiros permanecem em Dubai | G1', 'url': 'https://g1.globo.com/sp/sao-jose-do-rio-preto-aracatuba/noticia/2026/03/03/guerra-no-oriente-medio-fecha-espaco-aereo-e-moradores-do-interior-de-sp-sao-obrigados-a-permanecer-em-dubai.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'Trump: Empresas dos EUA estão produzindo armas em caráter emergencial | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/03/trump-guerra-ira-empresas-eua-produzindo-novos-armamentos-sob-ordens-emergenciais.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'Vídeo de explosão apocalíptica é incêndio na Coreia do Sul, não no Irã | G1', 'url': 'https://g1.globo.com/fato-ou-fake/noticia/2026/03/03/e-fake-que-video-mostre-explosao-apocaliptica-no-ira-apos-ataque-dos-eua-cena-exibe-incendio-de-2025-na-coreia-do-sul.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'O que está por trás do confronto entre Israel, Irã e Estados Unidos? | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/03/o-que-esta-por-tras-do-confronto-entre-israel-ira-e-estados-unidos-e-o-que-esperar.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'FOTO: fumaça cobre ilha artificial em Dubai após míssil interceptado | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/03/imagem-aerea-mostra-incendio-proximo-a-famosa-ilha-artificial-em-formato-de-palmeira-em-dubai-apos-interceptacao-de-missil.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'Sobe para 787 número de mortos no Irã por ataques dos EUA e de Israel, diz mídia estatal iraniana | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/03/sobe-para-787-mortos-ira-guerra-eua-israel.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'Guerra EUA e Israel x Irã: casal de Brasília tem viagem interrompida | G1', 'url': 'https://g1.globo.com/df/distrito-federal/noticia/2026/03/03/guerra-no-oriente-medio-casal-de-brasilia-tem-viagem-interrompida-e-fica-preso-em-oma.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'Brasileiros no Oriente Médio relatam tensão e mísseis em conflito | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/03/brasileiros-relatos-oriente-medio-guerra-eua-ira.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'Israel avança tropas e faz operação na fronteira com o Líbano | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/03/israel-faz-incursoes-militares-fronteira-libano-diz-agencia-ministro-autoriza-avanco-terrestre.ghtml'}, {'date_published': 'Tue, 03 Mar 2026 00:00:00 GMT', 'title': 'Legendário impedido de deixar Dubai relembra dia do ataque | G1', 'url': 'https://g1.globo.com/am/amazonas/noticia/2026/03/03/legendario-impedido-de-deixar-dubai-apos-conflito-no-oriente-medio-relembra-dia-do-ataque-descemos-a-montanha-e-estourou-a-guerra.ghtml'}, {'date_published': 'Wed, 04 Mar 2026 00:00:00 GMT', 'title': 'Atleta cearense em Israel relata rotina em meio a conflito | G1', 'url': 'https://g1.globo.com/ce/ceara/noticia/2026/03/04/atleta-cearense-em-israel-relata-rotina-em-meio-a-conflito-ficar-nessa-aflicao-vai-me-deixar-doente.ghtml'}, {'date_published': 'Wed, 04 Mar 2026 00:00:00 GMT', 'title': 'Zé Felipe diz que cancelou viagem à Disney por causa de guerra | G1', 'url': 'https://g1.globo.com/go/goias/noticia/2026/03/04/ze-felipe-revela-que-cancelou-viagem-com-filhos-para-disney-por-causa-dos-conflitos-entre-eua-e-ira.ghtml'}, {'date_published': 'Wed, 04 Mar 2026 00:00:00 GMT', 'title': 'Conflito EUA, Israel e Irã: brasileiro relata rotina sob bombardeios | G1', 'url': 'https://g1.globo.com/pa/para/noticia/2026/03/04/tu-nao-consegue-dormir-brasileiro-conta-rotina-sob-bombardeios-e-sirenes-de-emergencia-em-meio-ao-conflito-entre-eua-israel-e-ira.ghtml'}, {'date_published': 'Wed, 04 Mar 2026 00:00:00 GMT', 'title': 'Brasileira fica retida em Hong Kong após cancelamento de voos | G1', 'url': 'https://g1.globo.com/sp/bauru-marilia/noticia/2026/03/04/conflito-no-oriente-medio-comissaria-brasileira-fica-retida-em-hong-kong-apos-cancelamento-de-voos-para-os-emirados-arabes.ghtml'}, {'date_published': 'Thu, 05 Mar 2026 00:00:00 GMT', 'title': 'Governo Trump pede ajuda à Ucrânia para lidar com drones no Oriente Médio | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/05/governo-trump-pede-ajuda-a-ucrania-para-lidar-com-drones-no-oriente-medio.ghtml'}, {'date_published': 'Thu, 05 Mar 2026 00:00:00 GMT', 'title': 'Libaneses fogem de Beirute em meio a ataques; mortos passam de 100 | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/05/libaneses-fogem-beirute-ataques-mortos-passam-100-hezbollah-nao-ira-se-render.ghtml'}, {'date_published': 'Thu, 05 Mar 2026 00:00:00 GMT', 'title': 'X suspenderá monetização de vídeos de guerra feitos com IA sem aviso | G1', 'url': 'https://g1.globo.com/tecnologia/noticia/2026/03/05/x-suspendera-monetizacao-de-videos-de-guerra-feitos-com-ia-sem-aviso.ghtml'}, {'date_published': 'Fri, 06 Mar 2026 00:00:00 GMT', 'title': 'Brasileiros retidos em navio em Dubai após ataques na região | G1', 'url': 'https://g1.globo.com/sp/mogi-das-cruzes-suzano/noticia/2026/03/06/casal-da-grande-sp-fica-retido-em-navio-de-cruzeiro-em-dubai-apos-ataques-na-regiao.ghtml'}, {'date_published': 'Fri, 06 Mar 2026 00:00:00 GMT', 'title': 'Casal de Poá retido em cruzeiro em Dubai consegue voo de repatriação | G1', 'url': 'https://g1.globo.com/sp/mogi-das-cruzes-suzano/noticia/2026/03/06/casal-da-grande-sp-retido-em-navio-de-cruzeiro-em-dubai-consegue-voo-de-repatriacao.ghtml'}, {'date_published': 'Fri, 06 Mar 2026 00:00:00 GMT', 'title': 'Foto de criança em míssil na Síria é real; veja imagens | G1', 'url': 'https://g1.globo.com/fato-ou-fake/noticia/2026/03/06/e-fato-foto-mostra-crianca-escalando-missil-na-siria-meio-a-conflito-no-oriente-medio.ghtml'}, {'date_published': 'Sun, 08 Mar 2026 00:00:00 GMT', 'title': 'Casal retido em navio de cruzeiro em Dubai chega à Espanha | G1', 'url': 'https://g1.globo.com/sp/mogi-das-cruzes-suzano/noticia/2026/03/08/casal-da-grande-sp-retido-em-navio-de-cruzeiro-em-dubai-chega-a-espanha.ghtml'}, {'date_published': 'Tue, 10 Mar 2026 00:00:00 GMT', 'title': 'Apostas em ataque dos EUA ao Irã levantam suspeitas de manipulação | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/10/apostas-ataque-eua-ira-levantam-suspeitas-informacao-privilegiada.ghtml'}, {'date_published': 'Tue, 10 Mar 2026 00:00:00 GMT', 'title': "Irã ameaça Trump: 'cuidado para não ser eliminado' | G1", 'url': 'https://g1.globo.com/mundo/noticia/2026/03/10/larijani-ameaca-trum-cuidado-para-nao-ser-eliminado.ghtml'}, {'date_published': 'Wed, 11 Mar 2026 00:00:00 GMT', 'title': 'Vídeo de gato abandonado em Dubai é anterior à guerra no Irã | G1', 'url': 'https://g1.globo.com/fato-ou-fake/noticia/2026/03/11/nao-e-bem-assim-guerra-no-ira-causou-abandono-de-pets-mas-video-de-gato-sozinho-em-apartamento-de-dubai-e-de-janeiro.ghtml'}, {'date_published': 'Thu, 12 Mar 2026 00:00:00 GMT', 'title': 'Casal de Poá retido em cruzeiro em Dubai retorna ao Brasil | G1', 'url': 'https://g1.globo.com/sp/mogi-das-cruzes-suzano/noticia/2026/03/12/casal-de-poa-retido-em-cruzeiro-em-dubai-desembarca-em-guarulhos.ghtml'}, {'date_published': 'Mon, 23 Mar 2026 00:00:00 GMT', 'title': 'Netanyahu diz que discutiu com Trump possível acordo com o Irã | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/23/netanyahu-diz-que-discutiu-com-trump-possivel-acordo-com-o-ira-teera-nega-negociacoes.ghtml'}, {'date_published': 'Mon, 23 Mar 2026 00:00:00 GMT', 'title': 'Após suspender ultimato, Trump reafirma que há diálogo com Irã | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/03/23/trump-diz-nao-reconhecer-mojtaba-khamenei-como-novo-lider-supremo-do-ira.ghtml'}, {'date_published': 'Tue, 24 Mar 2026 00:00:00 GMT', 'title': 'Negociação EUA e Irã: Petróleo sobe com incertezas sobre acordo | G1', 'url': 'https://g1.globo.com/economia/noticia/2026/03/24/eua-dizem-que-situacao-de-negociacao-com-ira-e-fluida-e-preco-do-petroleo-volta-a-subir.ghtml'}, {'date_published': 'Thu, 02 Apr 2026 00:00:00 GMT', 'title': 'Chefe do Pentágono pede saída do comandante do Exército dos EUA | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/04/02/chefe-do-pentagono-pede-saida-do-comandante-do-exercito-dos-eua-diz-site.ghtml'}, {'date_published': 'Tue, 07 Apr 2026 00:00:00 GMT', 'title': 'Dia decisivo para guerra tem novos ataques e Trump renovando ultimato | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/04/07/em-dia-decisivo-para-a-guerra-israel-eua-e-ira-trocam-ataques-e-trump-dobra-aposta-em-ultimato.ghtml'}, {'date_published': 'Tue, 07 Apr 2026 00:00:00 GMT', 'title': 'Ultimato de Trump para o Irã se aproxima do fim com promessa de ataque | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/04/07/acordo-ou-inferno-ultimato-de-trump-para-o-ira-se-aproxima-do-fim-com-promessa-de-bombardeios-a-pontes-e-usinas.ghtml'}, {'date_published': 'Wed, 08 Apr 2026 00:00:00 GMT', 'title': 'Trump x Irã: da ameaça de extermínio ao cessar-fogo - O Assunto #1696 | G1', 'url': 'https://g1.globo.com/podcast/o-assunto/noticia/2026/04/08/trump-x-ira-da-ameaca-de-exterminio-ao-cessar-fogo-o-assunto-1695.ghtml'}, {'date_published': 'Sat, 11 Apr 2026 00:00:00 GMT', 'title': 'O que se sabe sobre o 1º dia de negociações de paz entre Irã e EUA no Paquistão | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/04/11/o-que-se-sabe-sobre-o-1o-dia-de-negociacoes-de-paz-entre-ira-e-eua-no-paquistao.ghtml'}, {'date_published': 'Thu, 16 Apr 2026 00:00:00 GMT', 'title': "'Guerra não é videogame': embaixador do Brasil no Irã relata explosões, tremor de paredes e mortes no conflito | G1", 'url': 'https://g1.globo.com/mundo/noticia/2026/04/16/guerra-nao-e-videogame-embaixador-do-brasil-no-ira-relata-explosoes-tremor-de-paredes-e-mortes-no-conflito.ghtml'}, {'date_published': 'Fri, 17 Apr 2026 00:00:00 GMT', 'title': 'EUA x Irã: quatro cenários possíveis do que vem pela frente no conflito | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/04/17/eua-x-ira-quatro-cenarios-possiveis-do-que-vem-pela-frente-no-conflito.ghtml'}, {'date_published': 'Fri, 17 Apr 2026 00:00:00 GMT', 'title': 'Macron e Starmer realizam cúpula internacional sobre reabertura do Estreito de Ormuz sem presença dos Estados Unidos | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/04/17/macron-e-starmer-realizam-cupula-internacional-sobre-reabertura-do-estreito-de-ormuz-sem-presenca-dos-estados-unidos.ghtml'}, {'date_published': 'Fri, 17 Apr 2026 00:00:00 GMT', 'title': 'Líderes europeus planejam missão para garantir que Estreito de Ormuz siga aberto; Trump alfineta | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/04/17/lideres-europeus-planejam-missao-para-garantir-que-estreito-de-ormuz-siga-aberto-trump-alfineta.ghtml'}, {'date_published': 'Fri, 24 Apr 2026 00:00:00 GMT', 'title': 'EUA negam desejo de substituir Irã por Itália na Copa do Mundo | G1', 'url': 'https://g1.globo.com/mundo/noticia/2026/04/24/eua-negam-desejo-de-substituir-ira-por-italia-na-copa-do-mundo.ghtml'}], 'limit': 2000, 'offset': 0, 'results': [{'article_title': 'Sobe para 787 número de mortos no Irã por ataques dos EUA e de Israel, diz mídia estatal iraniana | G1', 'article_url': 'https://g1.globo.com/mundo/noticia/2026/03/03/sobe-para-787-mortos-ira-guerra-eua-israel.ghtml', 'chunk': 'Título: Sobe para 787 número de mortos no Irã por ataques dos EUA e de Israel, diz mídia estatal iraniana | G1\nPublicado: 2026-03-03\nTrecho: Guerra entre EUA e Israel contra Irã começou no sábado e tem gerado mortos dos três lados e em outros países do Oriente Médio. Capital Teerã tem sido bombardeada todos os dias desde então.\nCategorias: G1, Mundo\n\nO novo balanço de mortos foi divulgado no 4º dia da guerra entre EUA, Israel e Irã, e apenas algumas horas após o início de novos bombardeios israelenses contra a capital Teerã. Por isso, é possível que os mortos de ataques desta terça ainda não tenham sido contabilizados.\nA guerra começou no sábado com bombardeios no território iraniano que mataram o líder supremo Ali Khamenei e autoridades militares do país. Desde então, o Irã tem retaliado contra Israel, militares dos EUA e outros países do Oriente Médio, o que fez o conflito se expandir (leia mais abaixo).\nGuerra EUA e Israel x Irã\nEstados Unidos e Israel lançaram um grande ataque contra o Irã na manhã de sábado (28), o que deflagrou uma guerra entre os três países. Explosões foram registradas na capital Teerã e em diversas outras cidades iranianas.\nOs bombardeios mataram o líder supremo do Irã, o aiatolá Ali Khamenei, e outros membros de alto escalão da cúpula militar e de governo iraniano. Ao todo, quase 800 pessoas foram mortas desde o início dos ataqu', 'distance': 0.5667166540935361, 'rrf_score': 0.02987736900780379, 'text_rank': 5}, {'article_title': 'EUA x Irã: quatro cenários possíveis do que vem pela frente no conflito | G1', 'article_url': 'https://g1.globo.com/mundo/noticia/2026/04/17/eua-x-ira-quatro-cenarios-possiveis-do-que-vem-pela-frente-no-conflito.ghtml', 'chunk': 'Título: EUA x Irã: quatro cenários possíveis do que vem pela frente no conflito | G1\nPublicado: 2026-04-17\nTrecho: O cessar-fogo vai se manter e a diplomacia continuar, ou o Irã e os EUA estão caminhando para uma escalada controlada ou até mesmo para uma guerra mais ampla?\nCategorias: G1, Mundo\n\nEUA x Irã: quatro cenários possíveis do que vem pela frente no conflito — Foto: Getty Images\nO presidente dos Estados Unidos, Donald Trump, disse que o Irã concordou em entregar seu estoque de urânio enriquecido, uma das questões-chave nas possíveis negociações para encerrar a guerra.\nSegundo Trump, as negociações entre os dois países podem ser retomadas no fim de semana, com os governos americano e iraniano "muito próximos" de um acordo, segundo ele.\nO Irã não comentou as declarações de Trump.\nTrump disse ainda acreditar que uma extensão do cessar-fogo com o Irã, que deve expirar no começo da próxima semana, não seria necessária por conta da proximidade de um possível acordo.\nUm diálogo inicial entre os dois países, no fim de semana passado no Paquistão, foi encerrado no domingo sem avanços.\nDiante desse cenário, quais os possíveis rumos para o conflito?\nA seguir, quatro cenários possíveis para o que pode acontecer.\n1. Cessar-fogo frágil como pausa \'estratégica\'\nNo dia 7 de abril, Irã e EUA concordaram com u', 'distance': 0.5782469632959616, 'rrf_score': 0.029644268774703556, 'text_rank': 9}, {'article_title': 'Guerra EUA e Israel x Irã: casal de Brasília tem viagem interrompida | G1', 'article_url': 'https://g1.globo.com/df/distrito-federal/noticia/2026/03/03/guerra-no-oriente-medio-casal-de-brasilia-tem-viagem-interrompida-e-fica-preso-em-oma.ghtml', 'chunk': 'Título: Guerra EUA e Israel x Irã: casal de Brasília tem viagem interrompida | G1\nPublicado: 2026-03-03\nTrecho: Bruna e Marcos Moreira estava viajando do Vietnã para o Catar. Durante a rota, o espaço aéreo do Catar foi fechado e o avião precisou pousar em Omã.\nCategorias: G1, DF, Distrito Federal\n\nMarcos e outras pessoas ficaram horas nas filas da imigração. Segundo Bruna, a companhia aérea ofereceu suporte e um hotel pra eles ficarem em Omã.\nPara o Marcos, a maior dificuldade é a espera e o contato com a família, pois, em um primeiro momento, conseguiam comunicação apenas via SMS.\nO casal também conta que entrou em contato com a embaixada do Brasil em Omã. A embaixada respondeu rapidamente, disse que acompanha a situação tranquilizou o casal, dizendo que o país não costuma ter conflito.\nGuerra EUA e Israel x Irã\nEstados Unidos e Israel lançaram um grande ataque contra o Irã na manhã de sábado (28), o que deflagrou uma guerra entre os três países. Explosões foram registradas na capital Teerã e em diversas outras cidades iranianas.\nOs bombardeios mataram o líder supremo do Irã, o aiatolá Ali Khamenei, e outros membros de alto escalão da cúpula militar e do governo iraniano. Ao todo, quase 800 pessoas foram mortas desde o início dos ataques ao país, afirmou a organização humanitária Cres

In [4]:
df = pd.DataFrame(data["articles"])
df.head()

,date_published,title,url
0,"Sat, 28 Feb 2026 00:00:00 GMT",EUA x Irã: relembre a cronologia dos protestos...,https://g1.globo.com/mundo/noticia/2026/02/28/...
1,"Sat, 28 Feb 2026 00:00:00 GMT",Companhias aéreas suspendem voos para o Orient...,https://g1.globo.com/mundo/noticia/2026/02/28/...
2,"Mon, 02 Mar 2026 00:00:00 GMT",Grupo de médicos no Catar vive indefinição sob...,https://g1.globo.com/rs/rio-grande-do-sul/noti...
3,"Mon, 02 Mar 2026 00:00:00 GMT",Estados Unidos x Irã: veja o que é FATO e o qu...,https://g1.globo.com/fato-ou-fake/noticia/2026...
4,"Mon, 02 Mar 2026 00:00:00 GMT",Guerra EUA e Israel x Irã: empresário brasilei...,https://g1.globo.com/sp/ribeirao-preto-franca/...

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date_published  51 non-null     str
 1   title           51 non-null     str
 2   url             51 non-null     str
dtypes: str(3)
memory usage: 1.3 KB

In [7]:
df[["title", "date_published"]]

,title,date_published
0,EUA x Irã: relembre a cronologia dos protestos...,"Sat, 28 Feb 2026 00:00:00 GMT"
1,Companhias aéreas suspendem voos para o Orient...,"Sat, 28 Feb 2026 00:00:00 GMT"
2,Grupo de médicos no Catar vive indefinição sob...,"Mon, 02 Mar 2026 00:00:00 GMT"
3,Estados Unidos x Irã: veja o que é FATO e o qu...,"Mon, 02 Mar 2026 00:00:00 GMT"
4,Guerra EUA e Israel x Irã: empresário brasilei...,"Mon, 02 Mar 2026 00:00:00 GMT"
5,Secretário de Trump diz que guerra contra Irã ...,"Mon, 02 Mar 2026 00:00:00 GMT"
6,Brasileiros no Oriente Médio relatam medo após...,"Mon, 02 Mar 2026 00:00:00 GMT"
7,EUA x Irã: brasileiro que voava à Tailândia co...,"Mon, 02 Mar 2026 00:00:00 GMT"
8,Brasileiros em Dubai relatam tensão após alert...,"Mon, 02 Mar 2026 00:00:00 GMT"
9,EUA afirmam que seis militares americanos morr...,"Mon, 02 Mar 2026 00:00:00 GMT"
10,Legendários não conseguem sair de Dubai após c...,"Mon, 02 Mar 2026 00:00:00 GMT"
11,Grande leva de ataques ao Irã ainda está por v...,"Mon, 02 Mar 2026 00:00:00 GMT"
12,"Guerra entre EUA, Israel e Irã fecha aeroporto...","Mon, 02 Mar 2026 00:00:00 GMT"
13,Guerra fecha espaço aéreo e brasileiros perman...,"Tue, 03 Mar 2026 00:00:00 GMT"
14,Trump: Empresas dos EUA estão produzindo armas...,"Tue, 03 Mar 2026 00:00:00 GMT"
15,Vídeo de explosão apocalíptica é incêndio na C...,"Tue, 03 Mar 2026 00:00:00 GMT"
16,"O que está por trás do confronto entre Israel,...","Tue, 03 Mar 2026 00:00:00 GMT"
17,FOTO: fumaça cobre ilha artificial em Dubai ap...,"Tue, 03 Mar 2026 00:00:00 GMT"
18,Sobe para 787 número de mortos no Irã por ataq...,"Tue, 03 Mar 2026 00:00:00 GMT"
19,Guerra EUA e Israel x Irã: casal de Brasília t...,"Tue, 03 Mar 2026 00:00:00 GMT"
20,Brasileiros no Oriente Médio relatam tensão e ...,"Tue, 03 Mar 2026 00:00:00 GMT"
21,Israel avança tropas e faz operação na frontei...,"Tue, 03 Mar 2026 00:00:00 GMT"
22,Legendário impedido de deixar Dubai relembra d...,"Tue, 03 Mar 2026 00:00:00 GMT"
23,Atleta cearense em Israel relata rotina em mei...,"Wed, 04 Mar 2026 00:00:00 GMT"
24,Zé Felipe diz que cancelou viagem à Disney por...,"Wed, 04 Mar 2026 00:00:00 GMT"
25,"Conflito EUA, Israel e Irã: brasileiro relata ...","Wed, 04 Mar 2026 00:00:00 GMT"
26,Brasileira fica retida em Hong Kong após cance...,"Wed, 04 Mar 2026 00:00:00 GMT"
27,Governo Trump pede ajuda à Ucrânia para lidar ...,"Thu, 05 Mar 2026 00:00:00 GMT"
28,Libaneses fogem de Beirute em meio a ataques; ...,"Thu, 05 Mar 2026 00:00:00 GMT"
29,X suspenderá monetização de vídeos de guerra f...,"Thu, 05 Mar 2026 00:00:00 GMT"
30,Brasileiros retidos em navio em Dubai após ata...,"Fri, 06 Mar 2026 00:00:00 GMT"
31,Casal de Poá retido em cruzeiro em Dubai conse...,"Fri, 06 Mar 2026 00:00:00 GMT"
32,Foto de criança em míssil na Síria é real; vej...,"Fri, 06 Mar 2026 00:00:00 GMT"
33,Casal retido em navio de cruzeiro em Dubai che...,"Sun, 08 Mar 2026 00:00:00 GMT"
34,Apostas em ataque dos EUA ao Irã levantam susp...,"Tue, 10 Mar 2026 00:00:00 GMT"
35,Irã ameaça Trump: 'cuidado para não ser elimin...,"Tue, 10 Mar 2026 00:00:00 GMT"
36,Vídeo de gato abandonado em Dubai é anterior à...,"Wed, 11 Mar 2026 00:00:00 GMT"
37,Casal de Poá retido em cruzeiro em Dubai retor...,"Thu, 12 Mar 2026 00:00:00 GMT"
38,Netanyahu diz que discutiu com Trump possível ...,"Mon, 23 Mar 2026 00:00:00 GMT"
39,"Após suspender ultimato, Trump reafirma que há...","Mon, 23 Mar 2026 00:00:00 GMT"
40,Negociação EUA e Irã: Petróleo sobe com incert...,"Tue, 24 Mar 2026 00:00:00 GMT"
41,Chefe do Pentágono pede saída do comandante do...,"Thu, 02 Apr 2026 00:00:00 GMT"
42,Dia decisivo para guerra tem novos ataques e T...,"Tue, 07 Apr 2026 00:00:00 GMT"
43,Ultimato de Trump para o Irã se aproxima do fi...,"Tue, 07 Apr 2026 00:00:00 GMT"
44,Trump x Irã: da ameaça de extermínio ao cessar...,"Wed, 08 Apr 2026 00:00:00 GMT"
45,O que se sabe sobre o 1º dia de negociações de...,"Sat, 11 Apr 2026 00:00:00 GMT"
46,'Guerra não é videogame': embaixador do Brasil...,"Thu, 16 Apr 2026 00:00:00 GMT"
47,EUA x Irã: quatro cenários possíveis do que ve...,"Fri, 17 Apr 2026 00:00:00 GMT"
48,Macron e Starmer realizam cúpula internacional...,"Fri, 17 Apr 2026 00:00:00 GMT"
49,Líderes europeus planejam missão para garantir...,"Fri, 17 Apr 2026 00:00:00 GMT"
50,EUA negam desejo de substituir Irã por Itália ...,"Fri, 24 Apr 2026 00:00:00 GMT"

In [10]:
df["type"] = df["url"].apply(lambda x: "complementar")

In [11]:
df.to_csv("articles.csv", index=True)